# Generated by Django 3.0.5 on 2020-04-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default=0, max_length=36),
        ),
    ]
