# Generated by Django 3.0.5 on 2020-04-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20200402_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknumber',
            name='isbn_13',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
