# Generated by Django 3.0.5 on 2020-04-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20200402_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
